AWSTemplateFormatVersion: "2010-09-09"

Resources:
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./s3.yaml
      Parameters:
        BucketName: money-treck-app-bucket

  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./iam.yaml
      Parameters:
        UserName: MoneyTreckDeployUser
# Outputs:
#   BucketName:
#     Value: !GetAtt S3Stack.Outputs.BucketName

