AWSTemplateFormatVersion: "2010-09-09"

Resources:
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./s3.yml
      Parameters:
        BucketName: money-treck-app-bucket

  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./iam.yml
      Parameters:
        UserName: MoneyTreckDeployUser

Outputs:
  BucketName:
    Value: !GetAtt S3Stack.Outputs.BucketName

  WebsiteURL:
    Value: !GetAtt S3Stack.Outputs.WebsiteURL

  AccessKeyId:
    Value: !GetAtt IAMStack.Outputs.AccessKeyId

  SecretAccessKey:
    Value: !GetAtt IAMStack.Outputs.SecretAccessKey
