AWSTemplateFormatVersion: "2010-09-09"
Description: "Money Treck UI"

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "money-treck-${AWS::Region}-${AWS::AccountId}"
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
