name: Deploy MoneyTreck to s3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code # action to pull your repository's code
        uses: actions/checkout@v3

      # Install dependencies and build the app
      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      # Deploy CloudFormation stack
      - name: Deploy CloudFormation stack
        run: | # creates and updates the stack based on the template file
          aws cloudformation deploy \
          --template-file cloudformation.yaml \
          --stack-name money-treck-stack \
          --capabilities CAPABILITY_NAMED_IAM

      # Retrieve IAM credentials and AWS region from CloudFormation outputs
      - name: Get CloudFormation outputs
        id: outputs
        run: |
          STACK_OUTPUT=$(aws cloudformation describe-stacks \
            --stack-name money-treck-stack \
            --query "Stacks[0].Outputs" \
            --output json
          )
          echo "${STACK_OUTPUT}" > stack-outputs.json

      - name: Parse outputs for Github Actions
        id: parse
        run: |
          ACCESS_KEY_ID=$(jq -r '.[] | select(.OutputKey=="AccessKeyId") | .OutputValue' stack-outputs.json)
          SECRET_ACCESS_KEY=$(jq -r '.[] | select(.OutputKey=="SecretAccessKey") | .OutputValue' stack-outputs.json)
          BUCKET_REGION=$(jq -r '.[] | select(.OutputKey=="AWSRegion") | .OutputValue' stack-outputs.json)
          echo "::set-output name=access_key_id::$ACCESS_KEY_ID"
          echo "::set-output name=secret_access_key::$SECRET_ACCESS_KEY"
          echo "::set-output name=bucket_region::$BUCKET_REGION"

      # Configure AWS CLI
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ steps.parse.outputs.access_key_id }}
          aws-secret-access-key: ${{ steps.parse.outputs.secret_access_key }}
          aws-region: ${{ steps.parse.outputs.bucket_region }}

      # Sync Next.js files to the s3 bucket
      - name: Deploy files to s3
        run:
          | # uploads all the files from the build to the newly created bucket and makes the files publicly accessible
          BUCKET_NAME=$(aws cloudformation describe-stacks \
            --stack-name money-treck-stack \
            --query "Stacks[0].Outputs[?OutputKey=='BucketName'].OutputValue" \
            --output text
          )
          aws s3 sync ./out s3://$BUCKET_NAME --delete --acl public-read

      # Output s3 Website URL
      - name: Output S3 Website URL
        run: |
          WEBSITE_URL=$(aws cloudformation describe-stacks \
            --stack-name money-treck-stack \
            --query "Stacks[0].Outputs[?OutputKey=='WebsiteURL'].OutputValue" \
            --output text
          ) 
          echo "The app is deployed at $BUCKET_URL"
