name: Deploy MoneyTreck to s3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code # action to pull your repository's code
        uses: actions/checkout@v3

      # Install dependencies and build the app
      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      # Setup AWS CLI
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Create s3 bucket using CloudFormation
      - name: Create s3 Bucket
        run: |
          aws cloudformation deploy \
          --template-file s3_bucket.yaml \
          --stack-name money-treck-stack \
          --capabilities CAPABILITY_NAMED_IAM

      # Sync Next.js files to the s3 bucket
      - name: Deploy files to s3
        run: |
          BUCKET_NAME=$(aws cloudformation describe-stacks \
            --stack-name money-treck-stack \
            --query "Stacks[0].Outputs[?OutputKey=='BucketName'].OutputValue" \
            --output text
          )
          aws s3 sync ./out s3://$BUCKET_NAME --delete --acl public-read

      # Output s3 bucket URL
      - name: S3 Bucket URL
        run: |
          BUCKET_NAME=$(aws cloudformation describe-stacks \
            --stack-name money-treck-stack \
            --query "Stacks[0].Outputs[?OutputKey=='BucketName'].OutputValue" \
            --output text
          ) 
          echo "The app is deployed at https://$BUCKET_NAME.s3-website-${{ secrets.AWS_REGION }}.amazonaws.com"
